version: '3'
services:
  ticketbot: # Name of the service
    build: .
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000" # Map ports if necessary (update based on your app)
    restart: unless-stopped
